### PR TITLE
add telegram support

### PR DESCRIPTION
**Pull request by savushkin-yauheni**
Hi. What do you think about tg support ?

### CODE REVIEW

**Comment by rs-loves-bugs** [comment]
Thank you for you contribution and sorry for the late reply. 

I'll review this the next days and merge it.

**Comment by rs-loves-bugs** [comment]
@savushkin-yauheni I don't think Telegram supports simple webhooks the same way Slack and Discord do(or I'm having troubles finding the documention). Can you point me to the documentation you used to test this?

**Comment by savushkin-yauheni** [comment]
Hi @rs-loves-bugs 
Yeah, sure:

https://gist.github.com/dideler/85de4d64f66c1966788c1b2304b9caf1
https://gist.github.com/SanariSan/4c7cca1aef10dfe0e27e55cfd97e9a53

I'm using right now my pr to send notifications to tg. 

Regards.

**Comment by Sh4d0wHunt3rX** [comment]
Hey, thanks for the script and Telegram support : ) I'm not so techie, but for telegram it was not possible to use token instead of webhook? I'm using another script for different thing, it has telegram integration, so I just enter my chat id and token, then it can send me notification.

**Comment by savushkin-yauheni** [comment]
Hi @amiremami 
It's the same. The webhook uses bot token to send a message.

**Pull request merged**
